// src/components/input/button.tsx
import { ElementSize } from "@structs/size";
import React, { PropsWithChildren } from "react";
import styles from "./button.module.scss";


const Button: React.FC<PropsWithChildren<Props>> = ({
  children,
  size = "md",
  variant = "primary",
  type = "button",
  onClick = () => undefined,
}) => {

  return (
    <button
      className={styles.main}

      type={type}
      data-variant={variant}
      data-size={size}

      onClick={onClick}
    >
      {children}
    </button>
  );
};

export { Button };

interface Props {
  variant?: "primary" | "secondary";
  type?: "button" | "submit" | "reset";
  size?: ElementSize;
  onClick?: () => void | Promise<void>;
}

// src/components/input/Button.svelte
<script lang="ts">
    import type { HTMLButtonAttributes } from "svelte/elements";
    interface $$Props extends HTMLButtonAttributes {
        variant?: "primary" | "secondary";
        size?: "sm" | "md" | "lg";
    }

    export let variant = "primary";
    export let size = "md";
</script>

<button class="button" {...$$restProps} data-variant={variant} data-size={size}>
    <slot />
</button>

<style lang="scss">
    @use "./button.scss" as *;
</style>
